keys:
  - &master age1zhctscxnn9wl6mx5jxsrj5jth3vqws64cyjtydl0xdf9tmhmcayq8y6v5u
  - &adam_yk1 age1yubikey1qwwu3yu02yffwmk4jhmake2jtc2zzrt4jlvhs8uxff5u8q546rdhc4jq0y6
  - &adam_yk2 age1yubikey1q07dgp7ama6saclfh645f7uvejc4mudqnl54wa5mufr0qt5y6a5ku34vpxz
  - &hellespont age1pyrgtn9ujr949gf6vtd9j89tvmq449nvd2ys5y5uyq6fvfusva5sd9th95
  - &hyphasis age1t8q3fcnwu3lz6ahdp3zvnvt7r24lu9cphausgn8tqx4pzu9v2q7qafrjlz
  - &atlas age135mu8xpcae3fgs8a60ujjkt2xyjn4h8cvf6t9c9j8s4dhv45x9cqq05k55

creation_rules:
  - path_regex: ^secrets/default\.yaml$
    key_groups:
      - age:
        - *master
        - *adam_yk1
        - *adam_yk2
        - *atlas
        - *hyphasis
        - *hellespont

  - path_regex: ^secrets/atlas\.yaml$
    key_groups:
      - age: [*master, *adam_yk1, *adam_yk2, *atlas]

  - path_regex: ^secrets/hellespont\.yaml$
    key_groups:
      - age: [*master, *adam_yk1, *adam_yk2, *hellespont]

  - path_regex: ^secrets/hyphasis\.yaml$
    key_groups:
      - age: [*master, *adam_yk1, *adam_yk2, *hyphasis]

  - path_regex: ^secrets/.*$
    key_groups:
      - age: [*master, *adam_yk1, *adam_yk2]
