hello: ENC[AES256_GCM,data:u5nuuJKtvw==,iv:szuMPNZvl6qzray6TaYGfbK33oNc6TsNEfgz5YGrmc8=,tag:tERov/6TLbYn8EWr6iz6sg==,type:str]
passwd: ENC[AES256_GCM,data:bKhJuKFNvqJ+5re2v8zYTn9VG+KHHNtK5VuFGdgwjnpoljVccsRsfL7eLn4YXogvwcNqvAcTIw8BL+fSM2LAvhUyNnQPhtswCQ==,iv:ijqcz3n+cq4tdAr/dTlysgOS2sQGkbDmD7gnzENMxiw=,tag:oA/VKM6rZ3r/KK5XrCs0Rw==,type:str]
my-ssh:
    key: ENC[AES256_GCM,data:qvqbNTPd4c6IaXBj5LZAmTF5c6PyP/8FUTHT7ZZzPsi48bzYfOnXw4EVbgpUAaqJlbyf6Sd/ubEutjA6dG7A7FaFB4PmIFleLf1HfADRn7rq0+IKZhVwoRkQI6DswTJ7ZxGNAYPEgYcY3yDrDGTs/DCsDS4o46MvRFjIU+o4pidY3sILtOjz6sJy2Ubub7mTftWaj+kU4EbCzHFvt1OPflXcsx3fmUCjpjHEd86m+pcHJr1QTMSR9mHIE99U/tneP87RPm8nvmrXKfaFzAiWNFM2fqqamBK0IBibZgnMMd2TqVxTxXb3sX5Z2n3Jte234kigQpuFwyUp81nbofyGRTnOEhq5aJW0384W7a52JFj5VhLZKpYMuP/AvnRiFofUMVe/2Y34688mMXJ6UslnvyX8jCb5LyGf+L9OwlmHfpW4dTie5r2TzkaoDYnhsY4SHsrDgYQ3yFYogPGsUM6ZbV0G/mE+qNnJo20q3sJx5GglNSlvSkn05CL5Lcz02lxHXtJfRGwS9Z7auBq06TNC,iv:2p1Yh7LQbWKq7SE2Piu5MqcotxEcHv4+NM/esZQfvqo=,tag:BhjKBsOO2GrLCXDIuVT76w==,type:str]
    pub: ENC[AES256_GCM,data:PhSIFigbJXGlEWAZX5yYkgORFg5JIkLRwZRc2Vgo031h0k5LFRepNKjJseaXmRNkbJNksu8HALw7u1E0R5a2WepgjIH6pe/+WFuHINnAmcg=,iv:7nxsbgjaAHVE56nyNeutVrwBSMIBi1INvaGBk/ENBWQ=,tag:C+CPB7hhuvpKJgGSThA0gw==,type:str]
nebula:
    ca-key: ENC[AES256_GCM,data:oxhJ4hiFKw38BdrxOpipbN3Gjlt/zz/vZ+zcYvls6mNyILHbrpftcP9Wx+7/cbI42lY9EvfMnzp7k5/FeNfxAT0e7+dgJdauyFVIBSEkON/6w3D+L/HX51AG9DZlWgXqwpwyb+HOg4XJ5o/Hpp9NDEx/UpSzW1N/sWyBo6pOrS8l1LKaqwm9Ioq61uD1CttMQAiumukb4Sj3WVWMJB1XdHGXiKHIxFgK9oXB9Mwf,iv:QTIpD5H6shSAHbBpy+L+yKPSn3EAeUGWNxJZbjntFnM=,tag:aoRlehPZ50CMvTvEfOlXfg==,type:str]
    ca-crt: ENC[AES256_GCM,data:qGkEIHcJ1nL1R7V9tGW9LcRMOJR4x6r/ed1BqRfdvHJ1G6bhuMhhwqmEcbydp2HX5asPPoRmyYZIjZExHGSARmygWNiFvMH2exWxWEjAo94+fzMc7no6RO+1AijhqEKp2bvHemodStX22Jg5d3/MCYa53uBcu7QkdMNR+Y7FaVuJY8qH09nYVkoIdebCeLVPEg6sXd5BT8382TkG22FCJa0vv74gKjsP/jXjyWCkn78aAD8k7MgELi1V4rw+Aa4KmCd9RyPCGNK5WffNW/VZdRrjt7Vlp87+N1os0Rz7IYgRW7D/nhe3YD9xC0Fe0uTmWKiBbgzZtGU2fw/Ke5VMDdKRKtRZIUv2j3wW88/iAFYa3mPLa8KqZsp45GvXzQ==,iv:IoxpA/ttJ4C3Y6/yWECFt6Cc/gTth8ewrIJvkykZO0o=,tag:deEXh8P/6Fuz5C8NFnAq8g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzYmVsYXVLNWRDS1h2ckly
            MHRzbXoxNThxWFEvNmRvT203ZERub0NRd0hRCndLVVR6K0ZuVVpzWks5ZGNqWGoy
            TUhZOXExbVVSakJ3REpVZ3Q0cDFzNlUKLS0tIEp4RGp4YWI4L2l3cldjc2JiOFln
            Sm41UFg5bFBZckdzTlNSbmlYRnZFWjgKsZmCNk1LgaxqZnue76nmzdCZ+0LvAS1F
            buG3K40qCgHIawlAYGFrsc5E+hpO06I9lvF6Wrv1FSd3oeYLp+rKtA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zhctscxnn9wl6mx5jxsrj5jth3vqws64cyjtydl0xdf9tmhmcayq8y6v5u
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHhWYk5YQSBBckdDWjYy
            MHlpU0tEcWlwNW55MmpkNWpRa211WU5Pd2dST0ZwQlJ3UDJaZgpqM3AyZkFNVC92
            NjI4RUc4dWpoTjZVQlkya09HdkRCOERhMmYwRVhNdWtvCi0tLSArSHlHNUlHMEVt
            UUUrdVRYMWhMdFN5SHhxQkpidlJyZjlIQ1k2eDdWRkFzCjt/g9vP13mTxoQ1f/M2
            2UaB6FYGLzEiztilMhzCgnnMaDw7vT4Y735M1INmOxOrvL0fPyrhCMj3P/Zpouk/
            +wo=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qwwu3yu02yffwmk4jhmake2jtc2zzrt4jlvhs8uxff5u8q546rdhc4jq0y6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpyZXZtZyBBbWp4c3Ev
            ZUZldUhyWjhiaXBRcHArV2YyMkhWT1FkbWJ4aVozVXlsRmRvTApvc2Npek1KS21a
            c3FYUC8wS2lDU0lIaXZLUnpObUxkS2J6KzBQK3VoVjJvCi0tLSBVZm1KdW5Sd0FT
            b2hhc3hHeS8vMHFldEhUTU5DQWIxWWt1L1dtRjFTVUlnCldTI8/KqtQMpJVPh3r7
            N+LM89dOu7BU/fWR0sjKTY5qq90GV7fk6oWMZMFqgfqt2AenpMcIpUSFqEKpv15i
            eus=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q07dgp7ama6saclfh645f7uvejc4mudqnl54wa5mufr0qt5y6a5ku34vpxz
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1bnZVNWg2dmxVeStKdDBs
            bVFBbUpTeThtc2NzMFY1WlJWYWYxNWlXZVZFCkNremNOYlhYNkxxZmZpdVp2cENU
            RFlaNFRJTEpVQkJTamNzRXBidFAxN3cKLS0tIEZWenVTSkpTY2NxZUJyMFNYcUVp
            ZEQwYzdoNFdNb3IwYXgxaDJmUWZ2Y1UKP0r6HV+t1VBJ/1khsSZ1k62/RpJrMvkw
            70m/HiKfMh/7ZtgHx9rTev025gKlwoXnPks5s9xQ8rGiqGxksOBykA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age135mu8xpcae3fgs8a60ujjkt2xyjn4h8cvf6t9c9j8s4dhv45x9cqq05k55
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDc25uaksxaTVzelpHbDU0
            elkxTm56UHlLZ0VIT2dsOUpqbk9VZmN5NVRJCmZ2c2g3VElhS2dIQWZLTXc3dUVH
            QzBDbUg5Y0RGT1RVb1VtMU5aOHVBcXMKLS0tIEZVWVNvUnRCMWhXaWF4T25mZ0pP
            cXhyZVJPZVlXSDhiZXowdXZNRDUva2MKDgQi1F5L/Kgs4Vqt5+6dB5tyNtEb91n8
            8nUlnxy7FBt14bFlfVbQcAmcRj3SwFaL3qsRPKQY2G0NS6mBIHdNcw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t8q3fcnwu3lz6ahdp3zvnvt7r24lu9cphausgn8tqx4pzu9v2q7qafrjlz
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6cDBaREMwL09rdTkvU0k1
            L3VKNTZFN0M0UW5jUFhIUDdyR3VKaXFiVzNjCldCMm10ZG1ZbklHdTZST3dLcjZ2
            TFFxTFp5aXlTY3RwOUI4T2YxZUIwVncKLS0tIDZiMFVXYTZBbjQ3NytiTStERWd6
            dzQrekdBL0xJZTBtVnNBbzZ1MkNxWjQK/qYWLex8pmKPqq/3Ndf4Pb6U/uJUdau5
            B1U6v5VLpfd5/8yIvWGlXqzcIA9l7gXMvuVT8JtT/1rgOxbbVCdlug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pyrgtn9ujr949gf6vtd9j89tvmq449nvd2ys5y5uyq6fvfusva5sd9th95
    lastmodified: "2026-09-07T16:12:51Z"
    mac: ENC[AES256_GCM,data:Dbr23FMv5F/iXigGSFmfAzmiAGK/tQ0ilOX0lS8FsxKzx5H/igF06f2Cx2YB+hhwYFVurdpjYU0zC03PSdqhdrpWjEcIQ38ZlUzgNjKLqn10YQmI8FpHzeUxjwZLKRPa0cMaG4AsZzZ+0LicbWxvsx8z+HKtCzCLR4B6WIGwZpU=,iv:u5vMhBhfAd2rzpFQnE8i3VTa0cA/Q+MdM/Za8dOEr2k=,tag:M0a9QWJHTiSrz7rYEpEc3A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
