hello: ENC[AES256_GCM,data:u5nuuJKtvw==,iv:szuMPNZvl6qzray6TaYGfbK33oNc6TsNEfgz5YGrmc8=,tag:tERov/6TLbYn8EWr6iz6sg==,type:str]
passwd: ENC[AES256_GCM,data:bKhJuKFNvqJ+5re2v8zYTn9VG+KHHNtK5VuFGdgwjnpoljVccsRsfL7eLn4YXogvwcNqvAcTIw8BL+fSM2LAvhUyNnQPhtswCQ==,iv:ijqcz3n+cq4tdAr/dTlysgOS2sQGkbDmD7gnzENMxiw=,tag:oA/VKM6rZ3r/KK5XrCs0Rw==,type:str]
my-ssh:
    key: ENC[AES256_GCM,data:qvqbNTPd4c6IaXBj5LZAmTF5c6PyP/8FUTHT7ZZzPsi48bzYfOnXw4EVbgpUAaqJlbyf6Sd/ubEutjA6dG7A7FaFB4PmIFleLf1HfADRn7rq0+IKZhVwoRkQI6DswTJ7ZxGNAYPEgYcY3yDrDGTs/DCsDS4o46MvRFjIU+o4pidY3sILtOjz6sJy2Ubub7mTftWaj+kU4EbCzHFvt1OPflXcsx3fmUCjpjHEd86m+pcHJr1QTMSR9mHIE99U/tneP87RPm8nvmrXKfaFzAiWNFM2fqqamBK0IBibZgnMMd2TqVxTxXb3sX5Z2n3Jte234kigQpuFwyUp81nbofyGRTnOEhq5aJW0384W7a52JFj5VhLZKpYMuP/AvnRiFofUMVe/2Y34688mMXJ6UslnvyX8jCb5LyGf+L9OwlmHfpW4dTie5r2TzkaoDYnhsY4SHsrDgYQ3yFYogPGsUM6ZbV0G/mE+qNnJo20q3sJx5GglNSlvSkn05CL5Lcz02lxHXtJfRGwS9Z7auBq06TNC,iv:2p1Yh7LQbWKq7SE2Piu5MqcotxEcHv4+NM/esZQfvqo=,tag:BhjKBsOO2GrLCXDIuVT76w==,type:str]
    pub: ENC[AES256_GCM,data:PhSIFigbJXGlEWAZX5yYkgORFg5JIkLRwZRc2Vgo031h0k5LFRepNKjJseaXmRNkbJNksu8HALw7u1E0R5a2WepgjIH6pe/+WFuHINnAmcg=,iv:7nxsbgjaAHVE56nyNeutVrwBSMIBi1INvaGBk/ENBWQ=,tag:C+CPB7hhuvpKJgGSThA0gw==,type:str]
nebula:
    ca-key: ENC[AES256_GCM,data:oxhJ4hiFKw38BdrxOpipbN3Gjlt/zz/vZ+zcYvls6mNyILHbrpftcP9Wx+7/cbI42lY9EvfMnzp7k5/FeNfxAT0e7+dgJdauyFVIBSEkON/6w3D+L/HX51AG9DZlWgXqwpwyb+HOg4XJ5o/Hpp9NDEx/UpSzW1N/sWyBo6pOrS8l1LKaqwm9Ioq61uD1CttMQAiumukb4Sj3WVWMJB1XdHGXiKHIxFgK9oXB9Mwf,iv:QTIpD5H6shSAHbBpy+L+yKPSn3EAeUGWNxJZbjntFnM=,tag:aoRlehPZ50CMvTvEfOlXfg==,type:str]
    ca-crt: ENC[AES256_GCM,data:qGkEIHcJ1nL1R7V9tGW9LcRMOJR4x6r/ed1BqRfdvHJ1G6bhuMhhwqmEcbydp2HX5asPPoRmyYZIjZExHGSARmygWNiFvMH2exWxWEjAo94+fzMc7no6RO+1AijhqEKp2bvHemodStX22Jg5d3/MCYa53uBcu7QkdMNR+Y7FaVuJY8qH09nYVkoIdebCeLVPEg6sXd5BT8382TkG22FCJa0vv74gKjsP/jXjyWCkn78aAD8k7MgELi1V4rw+Aa4KmCd9RyPCGNK5WffNW/VZdRrjt7Vlp87+N1os0Rz7IYgRW7D/nhe3YD9xC0Fe0uTmWKiBbgzZtGU2fw/Ke5VMDdKRKtRZIUv2j3wW88/iAFYa3mPLa8KqZsp45GvXzQ==,iv:IoxpA/ttJ4C3Y6/yWECFt6Cc/gTth8ewrIJvkykZO0o=,tag:deEXh8P/6Fuz5C8NFnAq8g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnWXA4L3pZU3JsUHo3T3NN
            L0hqVVFSTjJLY0thSE9UR2JLZFJoSVYzU0hNCmk1Mlp6eDdsSVhyYjFzMWtxcGlP
            bjJMdUNrM3lGSEdGWEdYMk1VcFQ2WncKLS0tIEwrRk1YbllRYTJDTXVZVkQyNFJ4
            OVNHbWtSTGhOK2E2ZTZwclZPeFJBM0kKpvxCvCLy3+K0S0FYvM1Fv4BFj6RG+IX2
            xcj/zGFAcwi0gLuaDuiCoImN0evLmhRuK5FepkoDs2hH1KNJLApV/A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zhctscxnn9wl6mx5jxsrj5jth3vqws64cyjtydl0xdf9tmhmcayq8y6v5u
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHhWYk5YQSBBd1JSTGNa
            N2xseVVFMytEQ0VLZisrY0pWdmNPN0ViZmJnWEtwM2x0SkFmeApUaDVGNS9KN296
            YU5UWjZCTGszb0dvcm9QYkZKbDYzNWdsa0NDM3FIaEpVCi0tLSB0TDRRZ3ZzcGF1
            REE5R1lWUUZrK0J5N0F5ZWw4ZWNRd3d3NkZlZGpCeXB3CsZcQh9HJdzSbB+8eWCy
            vYeytGP6hiu0V5AQvFsDR3FKJmkEWLbAm+0f3ues4K2zsDRWkZlCINv8W2ii70A8
            1N8=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qwwu3yu02yffwmk4jhmake2jtc2zzrt4jlvhs8uxff5u8q546rdhc4jq0y6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpyZXZtZyBBMWtCSk8r
            ZHpYUXhIRnpROG9CL016NHY0ZEFoakk5WVIveUM0b1hmSDVrVgpqeTE3NDNVdEs4
            K3RiZzdDRUpudzVtMWRDUmRkcXZrUEtJZEc0U1R1K3NZCi0tLSB1TWorNFQwR3d6
            QjN1V3RxQ2ViRUNUR0hFYWxLS2VEb25JQzBLc0JGb25rCspd+xFPul8QgHlSNjWO
            52Lsef7QwSl7Mqk2AzcelZw21ze9VaKY2xEYcNTX77AUiUfa1rSI/LDaoCoBoTK4
            x/A=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q07dgp7ama6saclfh645f7uvejc4mudqnl54wa5mufr0qt5y6a5ku34vpxz
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdkRpelhEdEt1WForSGV0
            ZlNkR2tOaXg1MTJFTzU2S0FtemluamtwVmdNCmFJM3pqTGxmdG1ZTVlRT1hnR2Vz
            YVRUUE03RzdoRWtDVkhUWDQvZUoxcVkKLS0tIGxzK2NaQ0lvbW5GVUIwcGNyVTVB
            b3RTYUhsTjQwQVlSV29DOUxPVExnaEUK/sv/5AfgWdck2dY7FxEHLAp25ZB89VzB
            xC8i7r9PGZYKFEEPHc/ae/EsgUgbk9f9tdd4EZqkqaOCf0fVy8PBkg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q7g4fecwf53vcy6swhp39nkhaalfuamv6mhn4d939e9uj57hcqxq320fe8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBenpGb3NudlM0RHp1dzEy
            M2VpcjFhTGY2TkdhckMwTWRLeFcvNzdSRFhZCk5DaEF5dzZIVnp6THFtcXdBK3Jk
            bVY0alg3bXI0Wmgrd2s4VVhNZS9XdjgKLS0tIGJOTHU3akE3VzNyT2Q0T09lbmxP
            QTF1SnFzUEhGVGY4dEJFMlFFaStSckkKInV+WovTM6kXk54UatMPB6YOzSzMQq2P
            HBQjaRCmNeht4sxvLlcdBNBRR2Jd5iz1M/6GPlhpZrYbrEZxBpVTeg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t8q3fcnwu3lz6ahdp3zvnvt7r24lu9cphausgn8tqx4pzu9v2q7qafrjlz
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4QzVEM0NwUDBuNmRPVFAx
            SmhtbmYxNjdTYkVWaG41M0IzV2RyVkh0UzJNClUzWjZSSERXVTF0SlNnbTBSQndw
            NDUvV2ViK2VzanVWc0sycU9DbHZNNjAKLS0tIEkyYVhabGg3TTQ3b3NJZjdCaUVM
            SWdZKytLN2JGa0RzWnI1MDVqallzZ2MKM/ol++MuSATw79LP3z0KNXRBv3HhCBET
            gqgMqxhAHwRsjpBx+vHWsxmpVNQ9wldEn3TjYPCY9i093SW4bGlSiw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pyrgtn9ujr949gf6vtd9j89tvmq449nvd2ys5y5uyq6fvfusva5sd9th95
    lastmodified: "2026-09-07T16:12:51Z"
    mac: ENC[AES256_GCM,data:Dbr23FMv5F/iXigGSFmfAzmiAGK/tQ0ilOX0lS8FsxKzx5H/igF06f2Cx2YB+hhwYFVurdpjYU0zC03PSdqhdrpWjEcIQ38ZlUzgNjKLqn10YQmI8FpHzeUxjwZLKRPa0cMaG4AsZzZ+0LicbWxvsx8z+HKtCzCLR4B6WIGwZpU=,iv:u5vMhBhfAd2rzpFQnE8i3VTa0cA/Q+MdM/Za8dOEr2k=,tag:M0a9QWJHTiSrz7rYEpEc3A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
