hello: ENC[AES256_GCM,data:u5nuuJKtvw==,iv:szuMPNZvl6qzray6TaYGfbK33oNc6TsNEfgz5YGrmc8=,tag:tERov/6TLbYn8EWr6iz6sg==,type:str]
passwd: ENC[AES256_GCM,data:bKhJuKFNvqJ+5re2v8zYTn9VG+KHHNtK5VuFGdgwjnpoljVccsRsfL7eLn4YXogvwcNqvAcTIw8BL+fSM2LAvhUyNnQPhtswCQ==,iv:ijqcz3n+cq4tdAr/dTlysgOS2sQGkbDmD7gnzENMxiw=,tag:oA/VKM6rZ3r/KK5XrCs0Rw==,type:str]
my-ssh:
    key: ENC[AES256_GCM,data:qvqbNTPd4c6IaXBj5LZAmTF5c6PyP/8FUTHT7ZZzPsi48bzYfOnXw4EVbgpUAaqJlbyf6Sd/ubEutjA6dG7A7FaFB4PmIFleLf1HfADRn7rq0+IKZhVwoRkQI6DswTJ7ZxGNAYPEgYcY3yDrDGTs/DCsDS4o46MvRFjIU+o4pidY3sILtOjz6sJy2Ubub7mTftWaj+kU4EbCzHFvt1OPflXcsx3fmUCjpjHEd86m+pcHJr1QTMSR9mHIE99U/tneP87RPm8nvmrXKfaFzAiWNFM2fqqamBK0IBibZgnMMd2TqVxTxXb3sX5Z2n3Jte234kigQpuFwyUp81nbofyGRTnOEhq5aJW0384W7a52JFj5VhLZKpYMuP/AvnRiFofUMVe/2Y34688mMXJ6UslnvyX8jCb5LyGf+L9OwlmHfpW4dTie5r2TzkaoDYnhsY4SHsrDgYQ3yFYogPGsUM6ZbV0G/mE+qNnJo20q3sJx5GglNSlvSkn05CL5Lcz02lxHXtJfRGwS9Z7auBq06TNC,iv:2p1Yh7LQbWKq7SE2Piu5MqcotxEcHv4+NM/esZQfvqo=,tag:BhjKBsOO2GrLCXDIuVT76w==,type:str]
    pub: ENC[AES256_GCM,data:PhSIFigbJXGlEWAZX5yYkgORFg5JIkLRwZRc2Vgo031h0k5LFRepNKjJseaXmRNkbJNksu8HALw7u1E0R5a2WepgjIH6pe/+WFuHINnAmcg=,iv:7nxsbgjaAHVE56nyNeutVrwBSMIBi1INvaGBk/ENBWQ=,tag:C+CPB7hhuvpKJgGSThA0gw==,type:str]
nebula:
    ca-key: ENC[AES256_GCM,data:d5j1N0FWOdhKNZY+JUnZTwtDIkT1BUgr/l1rorgq+FD1Nm+Gd4hJfNA3vsQSQ+pGpAZCPyUUI2cuLeldf7tlJLTN6lLnywsdoG60DW7UHjbfls6KubknQYQbEUxzjap/NVelP0vQrPcaezhe5+vtnbrRzZC8fhoJtJBFXxwIuCisXv4EF7IuMHhJX68DULKy/q9WKYF9dWbApRuzuOt2AhC9kPJIO5DXFwsueXa/,iv:QCfvJglIBHewFNtLds708k410xBWIYaOrTnp0TEsDDg=,tag:yP2P71BWz1IiBD9Gy7HGmQ==,type:str]
    ca-crt: ENC[AES256_GCM,data:1qIxWSWVQQWxEt6EjALr8yruUXIn/jX3Uhm5MRkx+GGw16Sgrn6/usvMNu+SiM831eJXcnl/ttBlI8DoBN4/eodMvARhrxd70GBf4rItFsWV0uCJwZV6tSfAUPOyAm/1haODaWA/+tHCqpE3Lo1I48BGQxCajbIPrlnuOlaPe7QA6QgANwEyqZ1mFkD6msS9R+822UNKFmEDHbWKQM6A7vYP/PNPNiL+lqHSA6nnEFYUbf8fIavQStrKZOLVP9WXcXqpFAavMYxBSt49oG+hjKKEGI/yEXShw4EnOIB+b2xtXIj/ElfbrTyH19IWZrSOO1JFbbCSH082a61V+KnnTErx3+hQ,iv:H3t6goCVRsXclrerdMmFHYRyo7Mu/I1DSwu/wMM+x34=,tag:Bdp0yhZ9oBfpWjfKF5L6PA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCSjNvK3BZUXBJZGVOWHVL
            OU5EQzU3M253blQxajVyVittdWhUQzFKc1FrCjFwYVIzcWJZSXQxT2lKeTRNRTBx
            NVVtTlE5V0NTOCt2cFdKS1lnVmlwck0KLS0tIFZZdyt1TEg4dVVCSkFSQkNiVmRl
            Q254c0RzSnZxTTFQYktrN25TWUI3YUEK/RN1ebiJmP9bkT+dq/Hof77jd70riLMm
            J8TMfOQwc8gHYPIYH5T03VTFKOSqWiT0T20N1fVWTK5ybp3rKdorbg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zhctscxnn9wl6mx5jxsrj5jth3vqws64cyjtydl0xdf9tmhmcayq8y6v5u
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHhWYk5YQSBBOVgyTmIx
            emJzSDE5RjlIN0lNMDBUZW5jMGphRnhSditYeW9OZ3k2SmJhTgpGbnFhMGw2UEdi
            SDdDald1YjRaQWk4Y1RhZkRyUnY3YVRla2poYXprbm53Ci0tLSBTckxIUi9ac2pV
            VTFZUGlLdkY1bE9BVlN6ZGxvZUgrZHBHOThBTWFTdFV3Cs1OatdGJgfNteg06DGz
            VfjnJciW9+WY0WwpuzH/pcj8K92y3UIZ4ngh1x3lUh1C6ic2ZmQ9i5S9Qn4NAoZT
            s5s=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qwwu3yu02yffwmk4jhmake2jtc2zzrt4jlvhs8uxff5u8q546rdhc4jq0y6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpyZXZtZyBBMzlHV1k4
            REdNa1JzdW01Q20xWS9nR0hZSnNPaTk1WU56SzRGcndHT2JCVgpDZWRCVVdrRVRt
            eWxxRytseS8xeDZibW9NK1ROUWlxZEI3U0Vta1BXZTFZCi0tLSBwMGR3MHpUeXFV
            Z1JXUWlBYWhvUVlkVm9JaFA2Z2NrNTR5cWJWSnlickpzCuSHRwMBvOxj83PKc3vt
            vVK9sPmN/I8VRej9HpauR/laeLoGIBvvcopHsU89/ZvD3UkQyHeNFMLSxDshHNBR
            PM4=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q07dgp7ama6saclfh645f7uvejc4mudqnl54wa5mufr0qt5y6a5ku34vpxz
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkeUNoY3JFK3ZmVm5GYmhC
            OWVHQktjQ1d5RGNobUZ6QmdjQ05jbXhnenpBCndFaFlZNTdVc3RGSGhZL1AxVExN
            K1BSVTB3TkFoeEVuUXA4cXZheHlRQTAKLS0tIFN2aVF1SVZIMzhEV3NiY0hpSWZR
            NWRaL3N2WFNkODduMHpkOVc4aG1MdUUKpxWjb72Xot1VtvNvxty3K+NFFAWND7tc
            bb45fcxsWZzsOzm4/KH/cqTwYwUxJ/8fxJTDlIbHHWHa4+V4+tRIag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q7g4fecwf53vcy6swhp39nkhaalfuamv6mhn4d939e9uj57hcqxq320fe8
    lastmodified: "2026-09-07T14:46:19Z"
    mac: ENC[AES256_GCM,data:WhVyBe3rJeEGMn4zzdR2ANlu+Vj6FU8IrMb48+Bqz+rg+GBJCTgCcBLaJHQ73ml2gLFu9hTX9p510wfetXuUqH5psvr2OVtowQPYpb/dU+tCnyeTMM14+qy0JxAXb3MCB73M4MBLJzOEGy6JxmdKJQx3n1gmCpoSA6RRHjyGG2k=,iv:P3J3f9q0yRahrTI/owchjE8jEHlhbPBe317yVvdkbzc=,tag:l/TGsfYhGgPYNleInlOWDw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
